question_data = [
    {"question": "There are 2 player roles in Trouble in Terrorist Town.",
     "correct_answer": "False"},
    {"question": "In Undertale;, the main character of the game is Sans.",
     "correct_answer": "False"},
    {"question": "The PlayStation was originally a joint project between Sega and Sony that was a Sega Genesis with a disc drive.",
     "correct_answer": "False"},
    {"question": "In Terraria, you can craft the Cell Phone pre-hardmode.",
     "correct_answer": "True"},
    {"question": "Rebecca Chambers does not appear in any Resident Evil except for the original Resident Evil and the Gamecube remake.",
     "correct_answer": "False"},
    {"question": "Each piece in Tetris is called a tetris.",
     "correct_answer": "False"},
    {"question": "Gordon Freeman, the protagonist of &quot;Half-Life&quot;, is said to have once had a ponytail.",
     "correct_answer": "True"},
    {"question": "The 2005 video game &quot;Call of Duty 2: Big Red One&quot; is not available on PC.",
     "correct_answer": "True"},
    {"question": "In Pok&eacute;mon, Arbok evolves into Seviper.",
     "correct_answer": "False"},
    {"question": "&quot;Sonic the Hedgehog 2&quot; originally was going to have a time travel system.",
     "correct_answer": "True"}
]
